### ISSUE TITLE
How to Install Wordpress on Mac

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-wordpress#1]
In the past we have used MAMP: https://www.mamp.info/en/mamp/mac/
And that still appears to be the way to go: https://skillcrush.com/blog/install-wordpress-mac

But reading this forum thread: https://wordpress.org/support/topic/first-time-installing-wordpress-on-mac
It appears that "Local" is the new way the kids are doing it these days: https://localwp.com

https://localwp.com/features
![image](https://user-images.githubusercontent.com/194400/88331656-37b03400-cd25-11ea-9266-a940ca991f5d.png)

# Todo

+ [ ] investigate what the _easiest_ option is
+ [ ] install everything
+ [ ] test the site on `localhost`
+ [ ] inspect the DB schema using DBeaver https://github.com/dwyl/learn-postgresql/issues/43
+ [ ] view the _permissions_ for https://github.com/dwyl/auth/issues/86

**Comment by nelsonic** [comment]
Sadly, running WordPress on Heroku isn't a viable option:
[![image](https://user-images.githubusercontent.com/194400/88380277-2bb38900-cd9c-11ea-990d-c009645330bb.png)](https://youtu.be/d4EndQrrcPA)
https://youtu.be/d4EndQrrcPA

The repo used in this video is: https://github.com/mhoofman/wordpress-heroku which has been archived (_no longer maintained_) and was last updated in 2015

See: https://help.heroku.com/58GWW5CQ/can-i-use-wordpress-on-heroku
Wordpress expects the filesystem to be writeable. Heroku's filesystem is ephemeral, which is a best for scaling.
Also, Heroku doesn't have _free_ MySQL DB ... so: https://devcenter.heroku.com/articles/heroku-mysql

**Comment by nelsonic** [comment]
Looks like this could be an option: https://elements.heroku.com/addons/cleardb#pricing
![heroku-free-mysql](https://user-images.githubusercontent.com/194400/88382741-ff4e3b80-cda0-11ea-8ff4-383029f2ea2d.png)

**Comment by nelsonic** [comment]
Trying to download "**Local**": https://localwp.com 
Seems like an oversight that they don't know what OS I'm using. It's right there in my **`User Agent`** ... 
![image](https://user-images.githubusercontent.com/194400/88477471-268b4100-cf38-11ea-9dc2-c000268fd51a.png)

**Comment by nelsonic** [comment]
Wow. they demand personal details before I can _download_ ...
![image](https://user-images.githubusercontent.com/194400/88477502-6ce0a000-cf38-11ea-9d0e-cb66ebe7d015.png)
No reasoning or link to privacy policy. 🤦 

It works with dummy data. Just enter valid looking "test@test.com" and the download works:
![image](https://user-images.githubusercontent.com/194400/88477526-aa452d80-cf38-11ea-8aac-d0656b2e0a79.png)

Direct CND link without inputting any data:
https://cdn.localwp.com/releases-stable/5.6.6+4375/local-5.6.6-mac.dmg

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/88477554-f2fce680-cf38-11ea-82b2-e74509b6c80c.png)

# **736 Megabytes** to run **WORDPRESS**!?!
![image](https://user-images.githubusercontent.com/194400/88477559-03ad5c80-cf39-11ea-893b-4b38c39878e6.png)

**Comment by nelsonic** [comment]
Entire operating systems are smaller than this!!

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/88477585-348d9180-cf39-11ea-893c-fabb3a75dbf2.png)

I'm never comfortable running random apps on my Mac ... 💭

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/88477602-73234c00-cf39-11ea-900f-6371987badbf.png)

https://localwp.com/legal/

## Local Terms of Service

By clicking “I Agree” below, you are entering into a contract with WPEngine, Inc. on behalf of itself and its affiliates (“WP Engine,” “we,” “our,” or “us”) which defines your rights and obligations related to the Local software ("Software"). That contract is comprised of these Terms of Service and the Privacy Policy located at https://wpengine.com/legal/privacy/ (together, the “Agreement”). By using the Software, you agree to be bound fully by the terms of this Agreement. You do not have to accept this Agreement, but it is the only agreement which grants you any rights to the Software. If you do not accept this Agreement, you must uninstall all copies of the Software and may not use it for any purpose. The Software is licensed, not sold, and is protected by all applicable copyright and other intellectual property laws worldwide.

THIS AGREEMENT REQUIRES BINDING ARBITRATION AND RESTRICTS YOUR ABILITY TO PARTICIPATE IN A CLASS ACTION OR SIMILAR LEGAL PROCESS. PLEASE REVIEW SECTION 6 CAREFULLY TO UNDERSTAND YOUR RIGHTS.

License Rights; Restrictions. For the duration of this Agreement, you may (i) use the Software for its intended purpose in accordance with the documentation we make available to you from time to time, and (ii) make and distribute unmodified copies of the Software on condition that such copies include this Agreement and all trademark, copyright, and other applicable legal notices. You may not use the Software for any illegal purpose. You may not rent, lease, or sell the Software to third parties or use the Software as part of a time-sharing, outsourcing, or service bureau environment. Except as explicitly provided herein, you may not copy, adapt, reverse engineer, decompile, disassemble, or create derivative works of the Software for any reason. WPEngine, Inc. reserves all rights except for those explicitly granted to you herein.
Intellectual Property. WP Engine or its licensors own and shall continue to own all right, title, and interest in and to the Software, including all system-generated data, logs, modifications, improvements, upgrades, derivative works, and all intellectual property rights in and to any of the foregoing. To the extent the Software includes or incorporates any third-party software, such software shall be subject to those license terms which accompany the software. If you provide us with any feedback: such feedback is provided freely and without restriction; we are free to use and disclose such feedback for any purpose without an accounting to you or any other person; and we shall own all right, title, and interest in and to such feedback along with any changes, modifications, or upgrades we make to the Software or any other products or services that we develop or improve based on such feedback. Except for the express rights granted herein, we do not grant any other rights, express or implied, in any of our intellectual property.
Indemnification. You will indemnify, defend, and hold harmless WP Engine and its officers, directors, agents, and employees from and against any and all liabilities, obligations, losses, damages, penalties, fines, amounts in interest, and other expenses (including reasonable attorney fees) in connection with a claim or demand brought by a third party related to your breach of Section 1 above.
DISCLAIMER. THE SOFTWARE IS PROVIDED AS-IS, AS AVAILABLE, AND WITH ALL FAULTS. WE MAKE NO WARRANTIES OF ANY KIND AND SPECIFICALLY DISCLAIM ALL IMPLIED WARRANTIES INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, UNINTERRUPTED OR ERROR FREE SERVICE, AVAILABILITY, ACCURACY, AND ANY AND ALL IMPLIED WARRANTIES ARISING FROM STATUTE, COURSE OF DEALING, COURSE OF PEFORMANCE, OR USAGE OF TRADE TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.
LIMITATION OF LIABILITY. TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL HAVE NO LIABILITY: (I) WITH RESPECT TO THE SOFTWARE OR ANY OBLIGATIONS UNDER THE AGREEMENT, OR (II) FOR ANY CONSEQUENTIAL, EXEMPLARY, SPECIAL, INCIDENTAL OR PUNITIVE DAMAGES EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING THE FOREGOING, OUR MAXIMIUM AGGREGATE LIABILITY FOR ALL CLAIMS SHALL BE LIMITED TO THE FEES PAID BY YOU UNDER THE AGREEMENT IN THE 6 MONTHS PRIOR TO THE APPLICABLE CLAIM OR $100, WHICHEVER IS GREATER. THIS LIMITATION APPLIES TO ALL CAUSES OF ACTION INCLUDING, WITHOUT LIMITATION, BREACHES OF CONTRACT OR WARRANTY, NEGLIGENCE, STRICT LIABILITY, MISREPRESENTATIONS, AND OTHER TORTS. BOTH PARTIES ACKNOWLEDGE AND AGREE THAT THE REMEDIES AND LIMITATIONS HEREIN ARE REASONABLE ALLOCATIONS OF THE RISKS BETWEEN THEM. THE FEES REFLECT, AND ARE SET IN RELIANCE UPON, THIS ALLOCATION OF RISK AND THE EXCLUSION OF CONSEQUENTIAL DAMAGES SET FORTH IN THIS AGREEMENT.
Dispute Resolution. This Agreement is governed by the laws of the State of Texas without regard to its choice of law statutes. All disputes will be resolved by binding, individual arbitration under the American Arbitration Association’s rules. Judgment on the award rendered by the arbitrator may be entered in any court having competent jurisdiction. Any provision of applicable law notwithstanding, the arbitrator will not have authority to award damages, remedies, or awards that conflict with this Agreement. WP Engine will pay all arbitration fees (excluding attorneys’ fees) for claims less than $10,000 and will not seek its attorneys’ fees and costs in arbitration unless the arbitrator determines that your claim or defense is frivolous. YOU MAY OPT OUT OF THIS AGREEMENT TO ARBITRATE. If you do so, neither party may require the other to participate in an arbitration proceeding. To opt out, you must notify us in writing at the address provided for legal notices herein within 30 days of the date that you first became subject to this arbitration provision. You must include your name, contact information, and a clear statement that you wish to opt out of this arbitration agreement. If you choose to opt out, or if this Section is found to be unenforceable for any reason: (i) any disputes must be brought in the state or federal courts located in Travis County, Texas; and (ii) no claim may be brought as a class or collective action and you may not actively assert a claim arising out of the Agreement as a member of a class or collective action. The United Nations Convention on the International Sale of Goods shall not govern the Agreement.
Miscellaneous. Agreement; Termination. This Agreement represents the entire understanding between the parties with respect to its subject matter and supersedes any previous communication or agreement that may exist. No waiver of a right, remedy, or power set out in the Agreement shall be effective unless provided in a writing signed by the waiving party. Either party may terminate this Agreement at any time for any reason, and any violation of the terms of this Agreement by you shall operate as an automatic termination of the Agreement. Upon termination, you shall no longer have any right or license to the Software, and you must immediately cease use of the Software and destroy all copies in your possession. Notice. Notices will be effective as of the date and time delivered or, in the case of notices delivered by post, 5 business days after being mailed to the designated address by first class mail. Notices to you shall be made via the Software or to any available contact information you have provided to us. Notices to us should be delivered to WP Engine, 504 Lavaca Street, Suite 1000, Austin, TX 78701, ATTN: Legal Department. Severability. Any provision in the Agreement that is held to be illegal or unenforceable in any jurisdiction shall be effective only up to the extent of such illegality or unenforceability, if possible, and shall not invalidate the remaining provisions of the paragraph or the Agreement. To the largest extent possible, the illegal or unenforceable provision shall be restated to reflect the parties’ intent. Survival. Any provision of the Agreement that contemplates performance or observance subsequent to termination or expiration of the Agreement (including, without limitation, confidentiality, limitation of liability, and indemnification) survive termination or expiration and continue in full force and effect. Third-Party Beneficiaries; Relationships. There are no third-party beneficiaries to the Agreement. Nothing contained in the Agreement shall be deemed or construed as creating a joint venture or partnership between the parties. Neither party is authorized as an agent, employee, or legal representative of the other by virtue of the Agreement nor authorized to make any representations, claims, or warranties on behalf of the other party.

**Comment by nelsonic** [comment]
Homepage:
![image](https://user-images.githubusercontent.com/194400/88477645-b5e52400-cf39-11ea-91e8-e2a43688bd42.png)

Create new site:
![image](https://user-images.githubusercontent.com/194400/88477653-c72e3080-cf39-11ea-83a8-64ceaf6df192.png)

Accept the default version of PHP 🤮  + MySQL:
![image](https://user-images.githubusercontent.com/194400/88477658-d319f280-cf39-11ea-8809-34a9fb068aeb.png)

Setup Wordpress:
![image](https://user-images.githubusercontent.com/194400/88477685-00ff3700-cf3a-11ea-9c17-38e7b5ddda92.png)

![image](https://user-images.githubusercontent.com/194400/88477691-0c526280-cf3a-11ea-85e2-5cc16efec438.png)

Overview:
![image](https://user-images.githubusercontent.com/194400/88477728-4b80b380-cf3a-11ea-8a22-f88bd8b0fe54.png)

Default site homepage:
![image](https://user-images.githubusercontent.com/194400/88477716-3ad03d80-cf3a-11ea-8f2e-ed51485f10be.png)


Open Database admin:

![image](https://user-images.githubusercontent.com/194400/88477742-6eab6300-cf3a-11ea-89c7-ba41ca2b2ced.png)

**Comment by nelsonic** [comment]
**`wp_users`** table: http://localhost:10005/?username=root&db=local&select=wp_users
![image](https://user-images.githubusercontent.com/194400/88477790-e1b4d980-cf3a-11ea-9d3b-034866a8b8db.png)

I'm _reminded_ that **`wp_users`** has a column for **`user_login`**, **`user_nicename`** and **`display_name`** all of which are the same. Not confusing at all. 🤦  
See: https://wordpress.stackexchange.com/questions/127905/user-login-vs-user-nicename

**`wp_usermeta`**: http://localhost:10005/?username=root&db=local&select=wp_usermeta
![image](https://user-images.githubusercontent.com/194400/88477852-4a03bb00-cf3b-11ea-9b7c-ef3794684254.png)

Really not much insight here either.
